# Generated by Django 3.1.7 on 2021-05-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlacesRemember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Аватарка пользователя'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя места')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('latitude', models.FloatField(max_length=50, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=50, verbose_name='Долгота')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlacesRemember.profile')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
