# Generated by Django 3.1.7 on 2021-05-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlacesRemember', '0003_auto_20210514_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlacesRemember.profile'),
        ),
    ]
